weather/urls.py
from django.urls import path

from . import views

urlpatterns = [
    
    path('', views.index),
    path('<city_name>', views.details),

]

weather_site/urls.py
from django.contrib import admin
from django.urls import path, include
from weather import views

urlpatterns = [
    path('', include('weather.urls')),
    path('admin/', admin.site.urls),
    path('<city_name>', include('weather.urls')),
    ]

weather/models.py
from django.db import models

# Create your models here.
class MeteoData(models.Model):
    date = models.DateTimeField()  
    temperature = models.CharField(max_length=200)
    temperature_face = models.CharField(max_length=200)
    humidity = models.CharField(max_length=200)
    beaufort = models.CharField(max_length=200)
    direction = models.CharField(max_length=200)
    speed = models.CharField(max_length=200)
    icon = models.CharField(max_length=200)
    description = models.CharField(max_length=200)

    @staticmethod
    def create_objects_from_dictionary(dictionary):
        for key, value in dictionary.items():
            if value['temperature_face'] == '':
                value['temperature_face'] = value['temperature'] # in order not to be empty
            meteo_object = MeteoData(date = key, temperature = value['temperature'], temperature_face = value['temperature_face'], humidity = value['humidity'],
            beaufort=value['beaufort'], direction = value['direction'], speed=value['speed'], icon = value['icon'], description = value['description'])
            meteo_object.save()


class OpenWeatherData(models.Model):
    date = models.DateTimeField()
    temperature = models.CharField(max_length=200)  
    temperature_face = models.CharField(max_length=200)
    humidity = models.CharField(max_length=200)
    speed = models.CharField(max_length=200)
    icon = models.CharField(max_length=200)
    description = models.CharField(max_length=200)

    @staticmethod
    def create_objects_from_dictionary(dictionary):
        for key, value in dictionary.items():
            open_weather_object = OpenWeatherData(date = key, temperature = value['temperature'], temperature_face = value['temperature_face'], humidity = value['humidity'],
            speed=value['speed'], icon = value['icon'], description = value['description'])
            open_weather_object.save()

class WeatherData(models.Model):
    date = models.DateTimeField()
    meteo = models.OneToOneField( MeteoData, on_delete=models.CASCADE)
    open_weather = models.OneToOneField( OpenWeatherData, on_delete=models.CASCADE)

    @staticmethod
    def create_weather_data_object():
        meteo_all =  MeteoData.objects.all()
        open_weather_all = OpenWeatherData.objects.all()
        for meteo, open_weather in zip(meteo_all, open_weather_all): #prosoxi edw sumfwna me to json prepei na shiftarw parw to prwto stoixeio tou open_weather omws to site isxurizetai oti den xreiazetai ama sugkrizeis ta dedomena
            weather_data = WeatherData(date = meteo.date, meteo = meteo, open_weather = open_weather)
            weather_data.save()

class State(models.Model):
    name = models.CharField(max_length=200)

    @staticmethod
    def create_states_informations(dictionary):
        for state, cities in dictionary.items():
            if state != 'ΑΚΤΕΣ ΑΤΤΙΚΗΣ' and state != 'ΑΡΧΑΙΟΛΟΓΙΚΟΙ ΧΩΡΟΙ' and state != 'ΧΙΟΝΟΔΡΟΜΙΚΑ ΚΕΝΤΡΑ' and state != 'ΧΕΙΜΕΡΙΝΟΙ ΠΡΟΟΡΙΣΜΟΙ' and state != 'ΟΔΙΚΟ ΔΙΚΤΥΟ':
                state_object = State(name = state)
                state_object.save()
                for name, informations in cities.items():
                    city_object = City(state = state_object, name = name, identifier = informations['id'],longitude = informations['longitude'], latitude = informations['latitude'])
                    city_object.save()
    

class City(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    identifier = models.CharField(max_length=200)
    longitude = models.CharField(max_length=200)
    latitude = models.CharField(max_length=200)

weather/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import MeteoData, OpenWeatherData, WeatherData, City, State
from . import meteo
from . import open_weather
from . import cities_informations

import requests
import json
import datetime


def index(request, city_name = 'ΑΡΓΟΣ'):
        menu = State.objects.all()
        return render(request, 'weather/index.html', {'menu' : menu})

def details(request, city_name = 'ΑΡΓΟΣ'):
        
        try:  
                city_id = City.objects.get(name=city_name).identifier
        except:
                return render(request, 'weather/error.html')
        latitude  = City.objects.get(name=city_name).latitude
        longitude  = City.objects.get(name=city_name).longitude
        
        MeteoData.objects.all().delete()
        OpenWeatherData.objects.all().delete()
        WeatherData.objects.all().delete()
        try:
                MeteoData.create_objects_from_dictionary(meteo.main(city_id))
                OpenWeatherData.create_objects_from_dictionary(open_weather.get_dictionary(latitude, longitude))
                WeatherData.create_weather_data_object()
        except:
                return render(request, 'weather/error.html')
        
        
        all_weather_data = WeatherData.objects.all()
        
        java_list = []
        for data in OpenWeatherData.objects.all():
                # month have to be -1 because 00 is January
                java_list.append({'x': data.date.strftime("new Date(%Y, %m - 1, %d, %H, %M)"), 'y': data.temperature})
        
        
        dictionary = {
                'weather': all_weather_data, 'scart' : java_list, 'city_name' : city_name 
        }
        return render(request, 'weather/details.html', dictionary)

weather/templates/weather/details.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>coWeather</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->	
        <link rel="icon" type="{% static 'image/png' %}" href="{% static 'details_page/images/icons/icon_top.ico' %}"/>
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'details_page/vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'details_page/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'details_page/vendor/animate/animate.css' %}">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'details_page/vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'details_page/vendor/perfect-scrollbar/perfect-scrollbar.css' %}">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'details_page/css/util.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'details_page/css/main.css' %}">
    <!--===============================================================================================-->
	<link href="{% static 'front_page/css/style.css' %}" rel="stylesheet">
	<link href="{% static 'front_page/css/responsive.css' %}" rel="stylesheet">
    </head>
	<style>
		body {
			background-image: url('{% static "details_page/images/slider1.jpg" %}');
		}
	</style>

  <header>
    <!-- header-area start -->
    <div id="sticker" class="header-area">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-sm-12">

            <!-- Navigation -->
            <nav class="navbar navbar-default">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                <!-- Brand -->
                <a class="navbar-brand page-scroll sticky-logo" href="/">
                  <h1><span>co</span>Weather</h1>
                  <!-- Uncomment below if you prefer to use an image logo -->
                  <!-- <img src="img/logo.png" alt="" title=""> -->
								</a>
			  </div>
			  
              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse main-menu bs-example-navbar-collapse-1" style="display: inline-block">
                <ul class="nav navbar-nav navbar-right">
                  <li>
                    <a class="page-scroll" href="">{{city_name}}</a>
                  </li>
                </ul>
              </div>
              <!-- navbar-collapse -->
            </nav>
               
              
            <!-- END: Navigation -->
          </div>
        </div>
      </div>
    </div>
    <!-- header-area end -->
  </header>

	<br>
	<br>
	<br>
	<br>
	<br>

	<div class="limiter">
		<br>
		<h1 style="color:white;"> </h1>
		<div class="container-table100">
			<div class="wrap-table100">
				<div class="table100 ver1 m-b-110">
					<div class="table100-head">
						<table >
							<thead>
								<tr class="row100 head">
									<th class="cell100 column1">Ημερομηνία</th>
									<th class="cell100 column2">Ώρα</th>
									<th class="cell100 column3">meteo.gr</th>
									<th class="cell100 column4">openweathermap.org</th>
								</tr>
							</thead>
						</table>
					</div>

						<table  border="0">
							<tbody>
								<style>
									.tempText { font-weight: bold; display:block; font-size: x-large; left: 0px; top: 30px;}
									.subtext { font-size: smaller; }
									.desciption {
										font-size: smaller;
									}
									.blockContent {
										position:relative;
										top : -50px;
									}
									.blockPicture{
										position:relative;
										top : 0px;
										left : 0px;
										word-wrap: break-word;
									}
								</style>
								
								{% for data in weather%}
									<tr class="row100 body">
										{% language 'el' %}
										<td class="cell100 column1"> {{data.date.date|date:'l d/m'}} </td>
										<td class="cell100 column2">{{data.date.time|time:'H:i'}}</td>
										{% endlanguage %}
										<td class="cell100 column3">
											<table>
												<tbody>
													<tr>
														<td>
															<span style="font-size: x-large;font-weight: bold;"> {{data.meteo.temperature}}&#8451; <br/> </span>
														</td>
														<td>
															<figure class="image is-15x15">
																<img src={{data.meteo.icon}} alt="Image"  width="70" height= "70">
															</figure>
															<span style="font-size: smaller;">{{data.meteo.description}}</span>
														</td>
													</tr>
													<tr class="row100 body">
															<td colspan="2">
																<span style="font-size: smaller;float: left;">Αισθητή: {{data.meteo.temperature_face}}&#8451;</span>
																<span style="font-size: smaller;float: right;"> Υγρασία: {{data.meteo.humidity}}&#37 <br/></span>
																<span style="font-size: smaller;float: left;">Μπφ: {{data.meteo.beaufort}}  Κατ: {{data.meteo.direction}}  Ταχ: {{data.meteo.speed}} km/h</span>
															</td>
													</tr>
												</tbody>
											</table>
										</td>
										<td class="cell100 column4">
											<table>
												<tbody>
													<tr>
														<td>
															<span style="font-size: x-large;font-weight: bold;"> {{data.open_weather.temperature}}&#8451; <br/> </span>
														</td>
														<td>
															<figure class="image is-15x15">
																<img src={{data.open_weather.icon}} alt="Image"  width="70" height= "70">
															</figure>
															<span style="font-size: smaller;">{{data.open_weather.description|upper}}</span>
														</td>
													</tr>
													<tr>
															<td colspan="2">
																<span style="font-size: smaller;float: left;">Αισθητή: {{data.open_weather.temperature_face}}&#8451;</span>
																<span style="font-size: smaller;float: right;"> Υγρασία: {{data.open_weather.humidity}}&#37 <br/></span>
																<span style="font-size: smaller;float: left;">Ταχ: {{data.meteo.speed}} km/h</span>
															</td>
													</tr>
												</tbody>
											</table>
										</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
				</div>
			</div>
		</div>
	</div>
	<!--
	<div class="limiter"></div>
		<div class="container-table100">
			<div class="wrap-table100">
		<div id="chartContainer" style="left: 20px; width:100%; height:320px"></div>  
		<div id="addDataPoint"></div>
			</div>

		</div> 
	</div> 
	-->

<!--===============================================================================================-->	
<script src="{% static 'details_page/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'details_page/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'details_page/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'details_page/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'details_page/vendor/perfect-scrollbar/perfect-scrollbar.min.js' %}"></script>
	<script>
		$('.js-pscroll').each(function(){
			var ps = new PerfectScrollbar(this);

			$(window).on('resize', function(){
				ps.update();
			})
		});
			
		
	</script>
<!--===============================================================================================-->
	<script src="{% static 'details_page/js/main.js' %}"></script>
<!--===============================================================================================-->
	<script type="text/javascript" src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>
	<script type="text/javascript" src="https://canvasjs.com/assets/script/canvasjs.min.js"></script> 
	<script type="text/javascript">
	window.onload = function () {
		var chart = new CanvasJS.Chart("chartContainer", {
			backgroundColor: "#141414",
			title: {
				fontColor: "white",
				text: "5ήμερη Πρόγνωση Καιρού"
			},
			axisX:{ 
				lineColor: "white", 
				labelFontColor: "white",
				valueFormatString: "DD-M-H-mm"
			},
			axisY:{
				lineColor: "white", 
				labelFontColor: "white",
			},  
			data: [
			{
				type: "spline",
				dataPoints: []
			}
			]
		});

		chart.render();	

		$("#addDataPoint").ready(function () {
		var length = chart.options.data[0].dataPoints.length;
		{%for data in scart%}
			chart.options.data[0].dataPoints.push({x: {{data.x}}, y: {{data.y}}});
		{%endfor%}
		chart.render();

		}).click();
	}
	</script>


</body>
</html>

weather/templates/weather/error.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>coWeather</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->	
        <link rel="icon" type="{% static 'image/png' %}" href="{% static 'details_page/images/icons/icon_top.ico' %}"/>
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'details_page/vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'details_page/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'details_page/vendor/animate/animate.css' %}">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'details_page/vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'details_page/vendor/perfect-scrollbar/perfect-scrollbar.css' %}">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'details_page/css/util.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'details_page/css/main.css' %}">
    <!--===============================================================================================-->
	<link href="{% static 'front_page/css/style.css' %}" rel="stylesheet">
	<link href="{% static 'front_page/css/responsive.css' %}" rel="stylesheet">
    </head>
	<style>
		body {
			background-image: url('{% static "details_page/images/slider1.jpg" %}');
		}
	</style>

  <header>
    <!-- header-area start -->
    <div id="sticker" class="header-area">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-sm-12">

            <!-- Navigation -->
            <nav class="navbar navbar-default">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                <!-- Brand -->
                <a class="navbar-brand page-scroll sticky-logo" href="/">
                  <h1><span>co</span>Weather</h1>
                  <!-- Uncomment below if you prefer to use an image logo -->
                  <!-- <img src="img/logo.png" alt="" title=""> -->
								</a>
			  </div>
			  
              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse main-menu bs-example-navbar-collapse-1" style="display: inline-block">
                <ul class="nav navbar-nav navbar-right">
                  <li>
                    <a class="page-scroll" href="">ΟΥΠΣ κάτι πήγε στραβά</a>
                  </li>
                </ul>
              </div>
              <!-- navbar-collapse -->
            </nav>
           
              
            <!-- END: Navigation -->
          </div>
        </div>
      </div>
    </div>
    
    <!-- header-area end -->
  </header>
  <body> 
  <img src={% static "details_page/images/error.png" %} class="errorElement">
  </body>

weather/templates/weather/index.html
{% load static %}
{% load replace_tags %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>coWeather</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">



  <!-- Favicons -->
  <link rel="icon" type="{% static 'image/png' %}" href="{% static 'details_page/images/icons/icon_top.ico' %}"/>

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700|Raleway:300,400,400i,500,500i,700,800,900" rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="{% static 'front_page/lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{% static 'front_page/lib/nivo-slider/css/nivo-slider.css' %}" rel="stylesheet">
  <link href="{% static 'front_page/lib/owlcarousel/owl.carousel.css' %}" rel="stylesheet">
  <link href="{% static 'front_page/lib/owlcarousel/owl.transitions.css' %}" rel="stylesheet">
  <link href="{% static 'front_page/lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'front_page/lib/animate/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'front_page/lib/venobox/venobox.css' %}" rel="stylesheet">

  <!-- Nivo Slider Theme -->
  <link href="{% static 'front_page/css/nivo-slider-theme.css' %}" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="{% static 'front_page/css/style.css' %}" rel="stylesheet">

  <!-- Responsive Stylesheet File -->
  <link href="{% static 'front_page/css/responsive.css' %}" rel="stylesheet">


</head>

<body data-spy="scroll" data-target="#navbar-example">


  <header>
    <!-- header-area start -->
    <div id="sticker" class="header-area">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-sm-12">

            <!-- Navigation -->
            <nav class="navbar navbar-default">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".bs-example-navbar-collapse-1" aria-expanded="false">
										<span class="sr-only">Toggle navigation</span>
										<span class="icon-bar"></span>
										<span class="icon-bar"></span>
										<span class="icon-bar"></span>
									</button>
                <!-- Brand -->
                <a class="navbar-brand page-scroll sticky-logo" href="/">
                  <h1><span>co</span>Weather</h1>
                  <!-- Uncomment below if you prefer to use an image logo -->
                  <!-- <img src="img/logo.png" alt="" title=""> -->
								</a>
              </div>
              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse main-menu bs-example-navbar-collapse-1" id="navbar-example">
                <ul class="nav navbar-nav navbar-right">
                  <li>
                    <a onclick="showEllada()" class="page-scroll" >ΕΛΛΑΔΑ</a>
                  </li>
                </ul>
              </div>
              <!-- navbar-collapse -->
            </nav>
                <nav class="navbar navbar-default2" id = "EDDADA" display = "none">
                  <div class="collapse navbar-collapse main-menu bs-example-navbar-collapse-1" id="navbar-example">
                    <ul class="nav navbar-nav navbar-left">
                      {% for state in menu%}
                      <li>
                        <a class="page-scroll" onclick="showCities('{{ state.name|replace_space }}')" > {{state.name}} </a>
                      </li>
                      {% endfor %}
                    </ul>
                  </div>
                </nav>
                <hr id = "line" style="display: none;">
                {% for state in menu%}
                <nav class="navbar navbar-default2" name = "ΠΟΛΕΙΣ" id = {{state.name|replace_space}} display = "none">
                  <div class="collapse navbar-collapse main-menu bs-example-navbar-collapse-1" id="navbar-example">
                    <ul class="nav navbar-nav navbar-left">
                      {% for city in state.city_set.all %}
                        <li><a class="page-scroll"  href="{{city.name}}">{{city.name}}</a></li>
				              {% endfor %}
                    </ul>
                  </div>
                </nav>
                {% endfor %}
            <!-- END: Navigation -->
          </div>
        </div>
      </div>
    </div>
    <!-- header-area end -->
  </header>
  <!-- header end -->

  <!-- Start Slider Area -->
  <div id="home" class="slider-area">
    <div class="bend niceties preview-2">
      <div id="ensign-nivoslider" class="slides">
        <img src="{%static 'front_page/img/slider/slider1.jpg' %}" alt="" title="#slider-direction-1" />
        <img src="{%static 'front_page/img/slider/slider2.jpg' %}" alt="" title="#slider-direction-2" />
        <img src="{%static 'front_page/img/slider/slider3.jpg' %}" alt="" title="#slider-direction-3" />
      </div>

      <!-- direction 1 -->
      <div id="slider-direction-1" class="slider-direction slider-one">
        <div class="container">
          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="slider-content">
                <!-- layer 1 -->
                <div class="layer-1-1 hidden-xs wow slideInDown" data-wow-duration="2s" data-wow-delay=".2s">
                  <h2 class="title1">Μιά σελίδα για να συγκρίνεις προογνώσεις καιρού</h2>
                </div>
                <!-- layer 2 -->
                <div class="layer-1-2 wow slideInUp" data-wow-duration="2s" data-wow-delay=".1s">
                  <h1 class="title2">Ο Καιρός στην Ελλάδα</h1>
                </div>
                <!-- layer 3 -->
                <div class="layer-1-3 hidden-xs wow slideInUp" data-wow-duration="2s" data-wow-delay=".2s">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- direction 2 -->
      <div id="slider-direction-2" class="slider-direction slider-two">
        <div class="container">
          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="slider-content text-center">
                <!-- layer 1 -->
                <div class="layer-1-1 hidden-xs wow slideInUp" data-wow-duration="2s" data-wow-delay=".2s">
                  <h2 class="title1">5ήμερη πρόγνωση καιρού</h2>
                </div>
                <!-- layer 2 -->
                <div class="layer-1-2 wow slideInUp" data-wow-duration="2s" data-wow-delay=".1s">
                  <h1 class="title2">Τελευταίες Καιρικές Ενημέρωσεις</h1>
                </div>
                <!-- layer 3 -->
                <div class="layer-1-3 hidden-xs wow slideInUp" data-wow-duration="2s" data-wow-delay=".2s">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- direction 3 -->
      <div id="slider-direction-3" class="slider-direction slider-two">
        <div class="container">
          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="slider-content">
                <!-- layer 1 -->
                <div class="layer-1-1 hidden-xs wow slideInUp" data-wow-duration="2s" data-wow-delay=".2s">
                  <h2 class="title1">Οι καλύτερες προγνώσεις</h2>
                </div>
                <!-- layer 2 -->
                <div class="layer-1-2 wow slideInUp" data-wow-duration="2s" data-wow-delay=".1s">
                  <h1 class="title2">Πάνω απο 500 ελληνικές περιοχές </h1>
                </div>
                <!-- layer 3 -->
                <div class="layer-1-3 hidden-xs wow slideInUp" data-wow-duration="2s" data-wow-delay=".2s">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End Slider Area -->

    <div class="footer-area-bottom">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="copyright text-center">
              <p>
                &copy; Copyright <strong>eBusiness</strong>. All Rights Reserved
              </p>
            </div>
            <div class="credits">
              Designed by <a href="https://www.linkedin.com/in/ioannis-schoinochoritis/">Schoinochoritis Ioannis</a> and <a href="https://bootstrapmade.com/">BootstrapMade</a>
              <br>
              Back-End by <a href="https://www.linkedin.com/in/ioannis-schoinochoritis/">Schoinochoritis Ioannis</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

  <!-- JavaScript Libraries -->
  <script src="{% static 'front_page/lib/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'front_page/lib/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'front_page/lib/owlcarousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'front_page/lib/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'front_page/lib/knob/jquery.knob.js' %}"></script>
  <script src="{% static 'front_page/lib/wow/wow.min.js' %}"></script>
  <script src="{% static 'front_page/lib/parallax/parallax.js' %}"></script>
  <script src="{% static 'front_page/lib/easing/easing.min.js' %}"></script>
  <script src="{% static 'front_page/lib/nivo-slider/js/jquery.nivo.slider.js' %}" type="text/javascript"></script>
  <script src="{% static 'front_page/lib/appear/jquery.appear.js' %}"></script>
  <script src="{% static 'front_page/lib/isotope/isotope.pkgd.min.js' %}"></script>

  <!-- Contact Form JavaScript File -->
  <script src="{% static 'front_page/contactform/contactform.js' %}"></script>

  <script src="{% static 'front_page/js/main.js' %}"></script>
  <script>
    function showEllada() {
      var element = document.getElementById('EDDADA');
      if (element.style.display === "" || element.style.display === "none"){
        element.style.display = "block"
      }
      else{
        var elements = document.getElementsByName("ΠΟΛΕΙΣ");
        for(var i=0; i<elements.length; i++) {
          elements[i].style.display = "none";
        }
        document.getElementById("line").style.display = "none";
        document.getElementById('EDDADA').style.display = "none"
      }
    }

  



    function showCities(x) {
      
      var elements = document.getElementsByName("ΠΟΛΕΙΣ");
      for(var i=0; i<elements.length; i++) {
        elements[i].style.display = "none";
      }
      document.getElementById(x).style.display = "block";
      document.getElementById("line").style.display = "block";


    }

    </script>
</body>

</html>